// <auto-generated />
using BlazorApp.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Server.Migrations
{
    [DbContext(typeof(SinhVienContext))]
    partial class SinhVienContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorApp.Shared.Models.BangDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("DiemCuoiKy")
                        .HasColumnType("float");

                    b.Property<double>("DiemGiuaKy")
                        .HasColumnType("float");

                    b.Property<double>("DiemThuong")
                        .HasColumnType("float");

                    b.Property<double>("DiemTongKet")
                        .HasColumnType("float");

                    b.Property<int>("MSV")
                        .HasColumnType("int");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MSV");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("BangDiems", (string)null);
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"), 1L, 1);

                    b.Property<string>("GiaoVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNghanh")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaNghanh");

                    b.ToTable("Lops", (string)null);
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonHoc"), 1L, 1);

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMonHoc");

                    b.ToTable("MonHocs", (string)null);
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Nganh", b =>
                {
                    b.Property<int>("MaNghanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNghanh"), 1L, 1);

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNghanh");

                    b.ToTable("Nganhs", (string)null);
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.SinhVien", b =>
                {
                    b.Property<int>("MSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MSV"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.HasKey("MSV");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhViens", (string)null);
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.BangDiem", b =>
                {
                    b.HasOne("BlazorApp.Shared.Models.SinhVien", "SinhVien")
                        .WithMany("BangDiems")
                        .HasForeignKey("MSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp.Shared.Models.MonHoc", "MonHoc")
                        .WithMany("BangDiems")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Lop", b =>
                {
                    b.HasOne("BlazorApp.Shared.Models.Nganh", "Nganh")
                        .WithMany("Lops")
                        .HasForeignKey("MaNghanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nganh");
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.SinhVien", b =>
                {
                    b.HasOne("BlazorApp.Shared.Models.Lop", "Lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.MonHoc", b =>
                {
                    b.Navigation("BangDiems");
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.Nganh", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("BlazorApp.Shared.Models.SinhVien", b =>
                {
                    b.Navigation("BangDiems");
                });
#pragma warning restore 612, 618
        }
    }
}
